#!/bin/sh

status() { \
    # Module Storage
    storage="^c#d3869b^󰆼^c#b16286^$(df --human --output=avail /dev/mapper/cryptvg-root | sed -n '1!p')"
    
    # Module Network
    connection_type=$(ip route | awk '/default/ { gsub(/ /, "", $5); print substr($5,1,2); exit }')
    case $connection_type in
        en)
	    network="^c#b8bb26^󰈀 ^c#98971a^UP";;
	wl)
	    wlan=$(iwconfig wlan0 | grep -i quality | awk '{print $2}' | cut -d'=' -f2 | cut -d'/' -f1)
	    network="^c#b8bb26^󰖩 ^c#98971a^$wlan%";;
	ww)
	    wwan="98%"
	    network="^c#b8bb26^󰢾 ^c#98971a^$wwan";;	
    esac

    # Module Battery
    battery_health=$(cat /sys/class/power_supply/BAT0/capacity)
    charging=$(cat /sys/class/power_supply/AC/online)
    case $battery_health in
	[0-9])
	    case $charging in
		0)
		    battery_glyph="󰂎";;
		1)
		    battery_glyph="󰢟";;
	    esac;;
	1[0-9])
	    case $charging in
		0)
		    battery_glyph="󰁺";;
		1)
		    battery_glyph="󰢜";;
	    esac;;
	2[0-9])
	    case $charging in
	        0)
		    battery_glyph="󰁻";;
		1)
		    battery_glyph="󰂆";;
	    esac;;
	3[0-9])
	    case $charging in
		0)
		    battery_glyph="󰁼";;
		1)
		    battery_glyph="󰂇";;
	    esac;;
	4[0-9])
	    case $charging in
		0)
		    battery_glyph="󰁽";;
		1)
		    battery_glyph="󰂈";;
	    esac;;
	5[0-9])
	    case $charging in
                0)
                    battery_glyph="󰁾";;
                1)
                    battery_glyph="󰢝";;
            esac;;
	6[0-9])
	    case $charging in
                0)
                    battery_glyph="󰁿";;
                1)
                    battery_glyph="󰂉";;
            esac;;
        7[0-9])
	    case $charging in
                0)
                    battery_glyph="󰂀";;
                1)
                    battery_glyph="󰢞";;
            esac;;
        8[0-9])
	    case $charging in
                0)
                    battery_glyph="󰂁";;
                1)
                    battery_glyph="󰂊";;
            esac;;
        9[0-9])
	    case $charging in
                0)
                    battery_glyph="󰂂";;
                1)
                    battery_glyph="󰂋";;
            esac;;
	100)
	    case $charging in
                0)
                    battery_glyph="󰁹";;
                1)
                    battery_glyph="󰂄";;
            esac;;
    esac 
    battery="^c#fabd2f^$battery_glyph ^c#d79921^$battery_health%" 

    # Module Time
    hhmm=$(date +'%I:%M')
    ampm=$(date +'%p' | tr '[:upper:]' '[:lower:]')
    time="^c#8ec07c^󰥔 ^c#689d6a^$hhmm"

    # Statusline
    echo "$network^b#000000^  $battery^b#000000^  $storage^b#000000^  $time"
}

# Program Loop
while true
do
    xsetroot -name "$(status| tr '\n' ' ')"

    sleep 1m
done
